spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/estorefinal"
    username: root
    password: Letmehear04@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true